#!/bin/bash
clear

GREEN="\033[32m"; YELLOW="\033[1;33m"; RED="\033[0;31m"; REDL="\e[101m"; BLINK="\e[5m"; END="\033[0m"

printf $YELLOW                                                                            
printf " _|      _|  _|_|_|_|  _|_|_|_|_|  _|      _|    _|_|      _|_|    _|_|_|  \n"
printf " _|_|    _|  _|            _|      _|_|    _|  _|    _|  _|    _|  _|    _|\n"
printf " _|  _|  _|  _|_|_|        _|      _|  _|  _|  _|    _|  _|    _|  _|_|_|  \n"
printf " _|    _|_|  _|            _|      _|    _|_|  _|    _|  _|    _|  _|    _|\n"
printf " _|      _|  _|_|_|_|      _|      _|      _|    _|_|      _|_|    _|_|_|  \n"
printf "\n"
printf "=============================== NETNOOB 1.0 ===============================\n"
printf "============================= GITHUB/NARCOTIC =============================\n"
printf $END

printf "\n"

if [[ $EUID -ne 0 ]]
 then
  printf $BLINK
  printf "Run as Root!\n\n"
  printf $END
  exit
fi

printf "1. Get information about your computer and network\n"
printf "2. Get information about another computer or a network\n"
printf "3. Change your network settings\n"

printf "0. Exit ->\n\n"

read -p "NETNOOB : " sel1

if [ $sel1 = 0 ]
 then
  exit
fi

while [ $sel1 = 1 ]; do

  printf "=========================*==========*=========================\n"
  
  printf "\n"
  printf "1. Your IP & MAC address\n"
  printf "2. Your Network Statistics\n"
  printf "3. Your Network Interface\n"

  printf "\n"
  printf "0. Exit ->\n"
  printf "\n"

  read -p "NETNOOB : " sel2

  if [ $sel2 = 1 ]
   then
    printf $YELLOW
    arp -e
    printf "\n"
    printf $END
   fi

  if [ $sel2 = 2 ]
   then
    printf $YELLOW
    netstat
    printf "\n"
    printf $END
  fi

  if [ $sel2 = 3 ]
   then
    printf $YELLOW    
    printf "\n"
    sudo ethtool $(route | grep '^default' | grep -o '[^ ]*$')
    printf $END
  fi

  if [ $sel2 = 0 ]
   then
     exit
  fi
done

if [ $sel1 = 2 ]
 then
  read -p "Domain name or IP Address : " webaddr
fi

while [ $sel1 = 2 ]; do
  printf "=========================*==========*=========================\n"

  printf "\n"

  printf "1. IP Address\n"
  printf "2. Scan all ports\n"
  printf "3. Scan a specific port\n"
  printf "4. Scan most common 100 ports\n"
  printf "5. Find [CNAMES] Alias Domain Names\n"
  printf "6. Domain Information Groper\n"
  printf "7. Records\n"

  printf "\n"
  printf "0. Exit ->\n"
  printf "\n"

  read -p "NETNOOB : " sel2

  if [ $sel2 = 1 ]
   then
    printf $YELLOW
    sudo host $webaddr
    printf "\n"
    printf $END
   fi

  if [ $sel2 = 2 ]
   then
    printf $YELLOW
    sudo nmap $webaddr
    printf "\n"
    printf $END
  fi

  if [ $sel2 = 3 ]
   then
    read -p "Port Number : " port
    printf $YELLOW
    sudo nmap -p $port $webaddr 
    printf "\n"
    printf $END
  fi

  if [ $sel2 = 4 ]
   then
    printf $YELLOW
    sudo nmap -F $webaddr 
    printf "\n"
    printf $END
  fi

  if [ $sel2 = 5 ]
   then
    printf $YELLOW
    sudo host -t CNAME $webaddr
    printf "\n"
    printf $END
  fi

  if [ $sel2 = 6 ]
   then
    printf $YELLOW
    sudo dig $webaddr any
    printf $END
  fi

  if [ $sel2 = 7 ]
   then
    printf $YELLOW
    sudo whois $webaddr
    printf $END
  fi

  if [ $sel2 = 0 ]
   then
     exit
  fi
done

if [ $sel1 = 3 ]
 then
  printf "\n"
  printf $REDL
  printf "Changing network settings might cause problems in connectivity.\n"
  printf "Do not use this tool without proper understanding!\n" 
  printf $END
  printf "\n"
  read -p "Continue ? [Y/N] : " yesno
fi

if [[ $yesno = 'y' || $yesno = 'Y' ]]; then
 while [ $sel1 = 3 ]; do
   printf "=========================*==========*=========================\n"

   printf "\n"

   printf "1. Change IP address\n"
   printf "2. Change MAC address\n"

   printf "\n"
   printf "0. Exit ->\n"
   printf "\n"

   read -p "NETNOOB : " sel2

   if [ $sel2 = 1 ]
    then
     printf $YELLOW
     printf "Your current IP address is : \n\n"
     arp -e
     printf "\n"
     printf $END
     read -p "Your new IP address should be, XXX.XXX.XXX.XXX : " newip
     read -p "Your new Default Gateway should be, XXX.XXX.XXX.XXX : " newgateway
     printf "\n"
     ifconfig eth0 down
     ifconfig eth0 inet $newip
     route add default gw $newgateway
     printf "\n"
     printf $YELLOW
     printf "Your IP address has been changed to $newip"
     printf "\n"
     printf "Your Default Gateway has been changed to $newgateway"
     printf "\n\n"
     printf $END
    fi

   if [ $sel2 = 2 ]
    then 
     printf $YELLOW
     printf "Your current MAC address is : \n\n"
     arp -e
     printf "\n"
     printf $END
     read -p "Your new MAC address should be, XX:XX:XX:XX:XX:XX : " newmac
     printf "\n"
     ifconfig eth0 down
     macchanger -m $newmac eth0
     ifconfig eth0 up
     sleep 2
     printf $YELLOW
     printf "\n"
     printf "Your new MAC address is : $newmac"
     printf "\n\n"
     printf $END
   fi

   if [ $sel2 = 0 ]
    then
      exit
   fi
 done
else
 exit
fi
exit
# END OF THE PROGRAM
